[package]
name = "bencher_billing"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
# Local
bencher_valid = { path = "../../lib/bencher_valid" }
# Workspace
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }
# Crate
async-stripe = { version = "0.18", features = ["runtime-tokio-hyper"] }

[dev-dependencies]
pretty_assertions.workspace = true
rand.workspace = true
