[package]
name = "bencher_billing"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
# Crate
async-stripe = { version = "0.18", features = ["runtime-tokio-hyper"] }
