# https://www.gitpod.io/docs/references/gitpod-yml

# .vscode/extension.json
vscode:
  extensions:
    [
      "vscodevim.vim",
      "eamodio.gitlens",
      "rust-lang.rust-analyzer",
      "serayuzgur.crates",
      "wcrichton.flowistry",
      "tamasfe.even-better-toml",
      "yzhang.markdown-all-in-one",
      "redhat.vscode-yaml",
      "esbenp.prettier-vscode",
      "Syler.sass-indented",
      "osohq.oso",
      "TabNine.tabnine-vscode",
      "streetsidesoftware.code-spell-checker",
      "shardulm94.trailing-spaces",
      "mtxr.sqltools",
      "mtxr.sqltools-driver-sqlite",
      "ms-azuretools.vscode-docker",
    ]

# Commands to start on workspace startup
tasks:
  - name: Extensions Setup
    init: npm install sqlite3@4.2.0
  - name: Rust Setup
    before: cargo check
    init: rustup toolchain install nightly && rustup component add rustfmt
    command: cd services/api && cargo run
  - name: JavaScript Setup
    before: cd services/ui && npm install --include=dev
    command: npm x vite

# Ports to expose on workspace startup
ports:
  - name: Bencher API
    port: 61016
    onOpen: open-browser
  - name: Bencher UI
    port: 3000
    onOpen: open-browser
  - name: Vite HMR
    port: 3001
