# https://www.gitpod.io/docs/references/gitpod-yml

# .vscode/extension.json
vscode:
  extensions:
    [
      "vscodevim.vim",
      "eamodio.gitlens",
      "rust-lang.rust-analyzer",
      "serayuzgur.crates",
      "wcrichton.flowistry",
      "tamasfe.even-better-toml",
      "vadimcn.vscode-lldb",
      "rome.rome",
      "yzhang.markdown-all-in-one",
      "unifiedjs.vscode-mdx",
      "redhat.vscode-yaml",
      "Syler.sass-indented",
      "ZixuanChen.vitest-explorer",
      "osohq.oso",
      "GitHub.copilot",
      "TabNine.tabnine-vscode",
      "streetsidesoftware.code-spell-checker",
      "shardulm94.trailing-spaces",
      "mtxr.sqltools",
      "mtxr.sqltools-driver-sqlite",
      "ms-azuretools.vscode-docker",
      "ms-vscode.hexeditor",
    ]

# Commands to start on workspace startup
tasks:
  - name: General Setup
    command: ./scripts/start.sh
  - name: API Setup
    before: ./scripts/start_api.sh
    init: ./scripts/wasm_pack.sh
    command: |
      cd services/api
      cargo run
  - name: CLI Setup
    before: cd services/cli
    command: source ../../scripts/start_cli.sh
  - name: UI Setup
    before: cd services/ui
    command: ../../scripts/start_ui.sh

# Ports to expose on workspace startup
ports:
  - name: Bencher API
    port: 61016
    onOpen: ignore
  - name: Bencher UI
    port: 3000
    onOpen: ignore
  - name: Vite HMR
    port: 3001
    onOpen: ignore
