# https://www.gitpod.io/docs/references/gitpod-yml

# Commands to start on workspace startup
tasks:
  - name: Rust Setup
    init: cargo check
    command: cd services/api && cargo run api
  - name: JavaScript Setup
    init: cd services/ui && npm install --include=dev
    command: npm x vite

# Ports to expose on workspace startup
ports:
  - port: 61016
    name: Bencher API
    onOpen: open-browser
  - port: 3000
    name: Bencher UI
    onOpen: open-browser


