# https://www.gitpod.io/docs/references/gitpod-yml

# .vscode/extension.json
vscode:
  extensions:
    [
      "vscodevim.vim",
      "eamodio.gitlens",
      "rust-lang.rust-analyzer",
      "serayuzgur.crates",
      "wcrichton.flowistry",
      "tamasfe.even-better-toml",
      "yzhang.markdown-all-in-one",
      "unifiedjs.vscode-mdx",
      "redhat.vscode-yaml",
      "esbenp.prettier-vscode",
      "Syler.sass-indented",
      "dbaeumer.vscode-eslint",
      "ZixuanChen.vitest-explorer",
      "osohq.oso",
      "TabNine.tabnine-vscode",
      "streetsidesoftware.code-spell-checker",
      "shardulm94.trailing-spaces",
      "mtxr.sqltools",
      "mtxr.sqltools-driver-sqlite",
      "ms-azuretools.vscode-docker",
      "ms-vscode.hexeditor",
    ]

# Commands to start on workspace startup
tasks:
  - name: General Setup
    before: ./scripts/init.sh
    init: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    command: ./scripts/setup.sh
  - name: API Setup
    before: cd services/api
    command: ../../scripts/start_api.sh
  - name: UI Setup
    before: cd services/ui
    command: ../../scripts/start_ui.sh

# Ports to expose on workspace startup
ports:
  - name: Bencher API
    port: 61016
    onOpen: ignore
  - name: Bencher UI
    port: 3000
    onOpen: ignore
  - name: Vite HMR
    port: 3001
    onOpen: ignore
