version: "3.9"
services:
  bencher_api:
    build:
      context: ./services
      dockerfile: ./api/Dockerfile
    image: bencher-api
    container_name: bencher_api
    ports:
      - 8080:8080
    volumes:
      # This file needs to exist before calling `docker compose`
      # `touch ./services/api/bencher.db`
      - "./services/api/bencher.db:/bencher.db"
    environment:
      # This should be set to your own secret key
      # - BENCHER_SECRET_KEY=
      - BENCHER_DB=bencher.db

  bencher_ui:
    build:
      context: ./services/ui
      dockerfile: Dockerfile
    image: bencher-ui
    container_name: bencher_ui
    ports:
      - 80:3000
      - 3001:3001
    environment:
      # Set this to your actual host
      - VITE_BENCHER_API_URL=http://localhost:8080
    depends_on:
      - bencher_api
