[package]
name = "tableflow"
version = "0.1.0"
authors = ["Everett Pompeii <epompeii@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.htm

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
wasm-bindgen-cli = "0.2.69"
wasm-bindgen-test = "0.3.19"
cargo-make = "0.32.10"
cargo-watch = "7.4"
trunk = "0.7.4"
pretty_assertions = "0.7.2"

[dependencies]
anyhow = "1.0.40"
chrono = "0.4.19"
english-numbers = "0.3.3"
im = { version = "15.0.0", features = ["serde"] }
ron = "0.6.4"
seed = "0.8.0"
serde = "1.0.125"
ulid = { version = "0.4.1", features = ["uuid", "serde"] }

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Os']
