[workspace]
members = ["services/api", "services/cli", "lib/*"]

[workspace.package]
version = "0.2.27"
authors = ["Everett Pompeii <epompeii@protonmail.com>"]
edition = "2021"

[workspace.dependencies]
chrono = "0.4"
derive_more = "0.99"
email-address-parser = "1.0"
jsonwebtoken = "8.1"
lazy_static = "1.4"
literally = "0.1"
ordered-float = "3.2"
oso = "0.26"
pretty_assertions = "1.3"
schemars = { version = "0.8", features = ["uuid1"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slug = "0.1"
thiserror = "1.0"
tokio = "1.21"
url = "2.3"
uuid = "1.2"

# TODO use this to generate wasm builds
# https://github.com/bencherdev/bencher/issues/48
[profile.release-wasm]
inherits = "release"
opt-level = "s"
