[workspace]
members = ["services/api", "services/cli", "lib/*", "plus/*", "xtask"]

[workspace.package]
version = "0.2.39"
authors = ["Everett Pompeii <everett@bencher.dev>"]
edition = "2021"

[workspace.dependencies]
anyhow = "1.0"
chrono = "0.4"
clap = { version = "4.1", features = ["derive"] }
derive_more = "0.99"
jsonwebtoken = "8.2"
literally = "0.1"
once_cell = "1.16"
ordered-float = "3.4"
oso = "0.26"
pretty_assertions = "1.3"
rand = "0.8"
schemars = { version = "0.8", features = ["uuid1"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slug = "0.1"
thiserror = "1.0"
tokio = "1.24"
url = "2.3"
uuid = "1.3"

# TODO use this to generate wasm builds
# https://github.com/bencherdev/bencher/issues/48
[profile.release-wasm]
inherits = "release"
opt-level = "s"
