version: "3.9"
services:
  build_bencher_api:
    build:
      context: ./services
      dockerfile: ./api/build.Dockerfile
    image: build-bencher-api
    container_name: build_bencher_api

  bencher_api:
    build:
      context: ./services
      dockerfile: ./api/deploy.Dockerfile
    image: bencher-api
    container_name: bencher_api
    ports:
      - 61016:61016
    environment:
      # This should be set to your own secret key
      # - BENCHER_SECRET_KEY=
      - BENCHER_DB=bencher.db
      # This should be your replication credentials and endpoint
      # https://litestream.io/guides/#replica-guides
      # - BENCHER_ACCESS_KEY_ID=
      # - BENCHER_SECRET_ACCESS_KEY=
      # - BENCHER_REPLICA_URL=
    depends_on:
      - build_bencher_api

  bencher_ui:
    build:
      context: ./services/ui
      dockerfile: Dockerfile
    image: bencher-ui
    container_name: bencher_ui
    ports:
      - 80:3000
      - 3001:3001
    environment:
      # Set this to your actual host
      - VITE_BENCHER_API_URL=http://localhost:61016
    depends_on:
      - bencher_api
