version: "3.9"
services:
  bencher_api:
    image: epompeii/bencher-api:latest
    container_name: bencher_api
    ports:
      - 61016:61016
    volumes:
      - "./data:/data"
    environment:
      # This should be set to your own secret key
      # - BENCHER_SECRET_KEY=
      - BENCHER_DB=bencher.db

  bencher_ui:
    image: epompeii/bencher-ui:latest
    container_name: bencher_ui
    ports:
      - 80:3000
      - 3001:3001
    environment:
      # Set this to your actual host
      - VITE_BENCHER_API_URL=http://localhost:61016
    depends_on:
      - bencher_api
