version: "3.9"
services:

  nginx:
    build:
      context: ./local/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - cli 
      - fn_demo

  cli:
    build:
      context: .
      dockerfile: ./local/cli.Dockerfile
    image: bencher-cli
    container_name: bencher_cli

  fn_demo:
    build:
      context: ./functions/demo
      dockerfile: Dockerfile
    image: fn-demo
    container_name: fn_demo
    ports:
        - 2000:8080