version: "3.9"
services:
  bencher_api:
    build:
      context: ./services
      dockerfile: ./api/Dockerfile
    image: benhcer-api
    container_name: bencher_api
    ports:
        - 2048:8080
    environment:
      - BENCHER_DB=bencher.db
    depends_on:
      - minio

  bencher_ui:
    build:
      context: ./services/ui
      dockerfile: Dockerfile
    ports:
      - 4096:3000
    depends_on:
      - bencher_api

  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001

