version: "3.9"
services:

  envoy:
      build:
        context: ./local/envoy
        dockerfile: Dockerfile
      restart: always
      ports:
        - 800:10000
      depends_on:
        - cli

  nginx:
    build:
      context: ./local/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - cli 
      - fn_demo

  cli:
    build:
      context: .
      dockerfile: ./local/rust.Dockerfile
    image: bencher-cli
    container_name: bencher_cli

  fn_demo:
    build:
      context: .
      dockerfile: ./functions/demo/Dockerfile
    image: bencher-demo
    container_name: bencher_demo
    ports:
        - 2000:8080