version: "3.9"
services:
  bencher_api:
    build:
      context: ./services
      dockerfile: ./api/Dockerfile
    image: benhcer-api
    container_name: bencher_api
    ports:
      - 8080:8080
    environment:
      - BENCHER_DB=bencher.db

  bencher_ui:
    build:
      context: ./services/ui
      dockerfile: Dockerfile
    ports:
      - 80:3000
    depends_on:
      - bencher_api
