version: "3.9"
services:
  bencher_api:
    image: epompeii/bencher-api:latest
    container_name: bencher_api
    ports:
      - 8080:8080
    volumes:
      # This file needs to exist before calling `docker compose`
      # `touch ./bencher.db`
      - "./bencher.db:/bencher.db"
    environment:
      - BENCHER_DB=bencher.db

  bencher_ui:
    image: epompeii/bencher-ui:latest
    container_name: bencher_ui
    ports:
      - 80:3000
      - 3001:3001
    environment:
      # Set this to your actual host
      - VITE_BENCHER_API_URL=http://localhost:8080
    depends_on:
      - bencher_api
