version: "3.9"
services:

  nginx:
    build:
      context: ./services/local/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      # - cli 
      - postgres
      - fn_reports

  # cli:
  #   build:
  #     context: ./services
  #     dockerfile: ./cli/Dockerfile
  #   image: bencher-cli
  #   container_name: bencher_cli

  postgres:
    build:
      context: ./services/local/db
      dockerfile: Dockerfile
    image: bencher-postgres
    container_name: bencher_postgres
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  fn_reports:
    build:
      context: ./services
      dockerfile: ./api/reports/dev.Dockerfile
    image: fn-reports
    container_name: fn_reports
    ports:
        - 2001:8080