version: "3.9"
services:

  envoy:
      build:
        context: ./local/envoy
        dockerfile: Dockerfile
      restart: always
      ports:
        - 80:10000
      depends_on:
        - cli

  cli:
    build:
      context: .
      dockerfile: ./local/rust.Dockerfile
    image: bencher-cli
    container_name: bencher_cli