version: "3.9"
services:

  nginx:
    build:
      context: ./services/local/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      # - cli 
      # - fn_demo
      - fn_reports

  # cli:
  #   build:
  #     context: ./services
  #     dockerfile: ./cli/Dockerfile
  #   image: bencher-cli
  #   container_name: bencher_cli

  # fn_demo:
  #   build:
  #     context: ./services/functions
  #     dockerfile: ./demo/dev.Dockerfile
  #   image: fn-demo
  #   container_name: fn_demo
  #   ports:
  #       - 2000:8080

  fn_reports:
    build:
      context: ./services
      dockerfile: ./functions/reports/Dockerfile
    image: fn-reports
    container_name: fn_reports
    ports:
        - 2001:8080