version: "3.8"

services:
  exec:
    build:
      context: ./exec
      dockerfile: Dockerfile
    image: tf-exec
    container_name: exec
    volumes:
      - ./exec/data:/usr/src/exec/data
    ports:
      - 4040:8080
    environment:
      - ENDPOINT_ADDRESS=0.0.0.0
      - ENDPOINT_PORT=8080
      - DATA_PATH=/usr/src/exec/data
