version: "3.9"
services:
  bencher_api:
    build:
      context: ./services/api
      dockerfile: litestream.Dockerfile
    image: bencher-api-litestream
    container_name: bencher_api_litestream
    ports:
      - 61016:61016
      - 8118:8118
    environment:
      # Set configuration string or filepath
      # - BENCHER_CONFIG=
      # - BENCHER_CONFIG_PATH=
      # Set litestream configuration
      - LITESTREAM_DB_PATH=/data/bencher.db
      # - LITESTREAM_REPLICA_URL=
      # - AWS_ACCESS_KEY_ID=
      # - AWS_SECRET_ACCESS_KEY=

  bencher_ui:
    build:
      context: ./services/ui
      dockerfile: Dockerfile
    image: bencher-ui
    container_name: bencher_ui
    ports:
      - 3000:80
    depends_on:
      - bencher_api
