version: "3.9"
services:
  bencher_api:
    build:
      context: ./services/api
      dockerfile: litestream.Dockerfile
    image: bencher-api-litestream
    container_name: bencher_api_litestream
    ports:
      - 61016:61016
    environment:
      # Set configuration string or filepath
      # - BENCHER_CONFIG=
      # - BENCHER_CONFIG_PATH=
      - BENCHER_DB=bencher.db

  bencher_ui:
    build:
      context: ./services/ui
      dockerfile: Dockerfile
    image: bencher-ui
    container_name: bencher_ui
    ports:
      - 80:3000
      - 3001:3001
    environment:
      # Set this to your actual host
      - VITE_BENCHER_API_URL=http://localhost:61016
    depends_on:
      - bencher_api
