version: "3.9"
services:
  bencher_api_builder:
    build:
      context: .
      dockerfile: ./services/api/builder.Dockerfile
    image: bencher-api-builder
    container_name: bencher_api_builder

  bencher_api:
    build:
      context: ./services/api
      dockerfile: litestream.Dockerfile
    image: bencher-api-litestream
    container_name: bencher_api_litestream
    ports:
      - 61016:61016
    environment:
      # This should be set to your own secret key
      # - BENCHER_SECRET_KEY=
      - BENCHER_DB=bencher.db
      # This should be your replication credentials and endpoint
      # https://litestream.io/guides/#replica-guides
      # - BENCHER_ACCESS_KEY_ID=
      # - BENCHER_SECRET_ACCESS_KEY=
      # - BENCHER_REPLICA_URL=
    depends_on:
      - bencher_api_builder

  bencher_ui:
    build:
      context: ./services/ui
      dockerfile: Dockerfile
    image: bencher-ui
    container_name: bencher_ui
    ports:
      - 80:3000
      - 3001:3001
    environment:
      # Set this to your actual host
      - VITE_BENCHER_API_URL=http://localhost:61016
    depends_on:
      - bencher_api
