version: "3.9"
services:
  bencher_api:
    build:
      context: ./services/api
      dockerfile: local.Dockerfile
    image: bencher-api-local
    container_name: bencher_api_local
    ports:
      - 61016:61016
    volumes:
      - "./services/api/data:/data"
    environment:
      # This should be set to your own secret key
      # - BENCHER_SECRET_KEY=
      - BENCHER_DB=bencher.db
    depends_on:
      - bencher_api_builder

  bencher_ui:
    build:
      context: ./services/ui
      dockerfile: Dockerfile
    image: bencher-ui
    container_name: bencher_ui
    ports:
      - 80:3000
      - 3001:3001
    environment:
      # Set this to your actual host
      - VITE_BENCHER_API_URL=http://localhost:61016
    depends_on:
      - bencher_api
