newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
match_block_trailing_comma = true
imports_layout = "Vertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
enum_discrim_align_threshold = 10
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 10
wrap_comments = true
