[package]
name = "exec"
version = "0.1.0"
authors = ["TableFlow"]
edition = "2018"

[dependencies]
tide = "0.16.0"
async-std = { version = "1.9", features = ["attributes"] }
serde = "1.0.125"
serde_json = "1.0.64"
http-types = "2.11.0"
