[package]
name = "bencher_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
seed = []

[dependencies]
bencher_json = { path = "../lib/bencher_json" }
clap = { version = "3.2", features = ["derive"] }
git2 = "0.15"
nom = "7.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.3"
thiserror = "1.0"
reqwest = { version = "0.11", features = ["json"] }
url = "2.3"
tokio = { version = "1.21", features = ["full"] }
email-address-parser = "1.0"
async-trait = "0.1"
chrono = { version = "0.4" }
uuid = "1.1"
smart-default = "0.6"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "2.1"
pretty_assertions = "1.3"

[[bin]]
name = "bencher"
path = "src/main.rs"
