[package]
name = "bencher_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
seed = []

[dependencies]
bencher_json = { path = "../lib/bencher_json" }
clap = { version = "3.2.16", features = ["derive"] }
git2 = "0.15.0"
nom = "7.1.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
tempfile = "3.3.0"
thiserror = "1.0.31"
reqwest = { version = "0.11.10", features = ["json"] }
open = "2.1.2"
url = "2.2.2"
tokio = { version = "1.18.2", features = ["full"] }
email-address-parser = "1.0.3"
async-trait = "0.1.56"
chrono = { version = "0.4.20" }
uuid = "1.1.2"
smart-default = "0.6.0"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "2.1"
pretty_assertions = "1.3.0"

[[bin]]
name = "bencher"
path = "src/main.rs"
