[package]
name = "bencher_cli"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
default = ["plus"]
docs = ["dep:clap_mangen"]
plus = ["bencher_json/plus"]
seed = []

[dependencies]
# Local
bencher_adapter = { path = "../../lib/bencher_adapter" }
bencher_json = { path = "../../lib/bencher_json" }
# Workspace
chrono.workspace = true
clap.workspace = true
literally.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
url.workspace = true
uuid.workspace = true
# Crate
async-trait = "0.1"
clap_mangen = { version = "0.2", optional = true }
reqwest = { version = "0.11", default-features = false, features = [
    "json",
    "rustls-tls",
] }

[dev-dependencies]
# Workspace
pretty_assertions.workspace = true
# Crate
assert_cmd = "2.0"

[[bin]]
name = "bencher"
path = "src/main.rs"
