[package]
name = "bencher_cli"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
default = ["plus"]
docs = ["dep:clap_mangen"]
plus = ["bencher_json/plus"]
seed = []

[dependencies]
# Workspace
async-trait.workspace = true
bencher_adapter.workspace = true
bencher_json.workspace = true
chrono.workspace = true
clap.workspace = true
literally.workspace = true
rand.workspace = true
reqwest = { workspace = true, default-features = false, features = [
    "json",
    "rustls-tls",
] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
url.workspace = true
uuid.workspace = true
# Crate
clap_mangen = { version = "0.2", optional = true }

[dev-dependencies]
# Workspace
pretty_assertions.workspace = true
# Crate
assert_cmd = "2.0"

[[bin]]
name = "bencher"
path = "src/main.rs"
