[package]
name = "bencher_cli"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
seed = []

[dependencies]
# Local
bencher_json = { path = "../lib/bencher_json" }
# Workspace
chrono.workspace = true
email-address-parser.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
url.workspace = true
uuid.workspace = true
# Crate
async-trait = "0.1"
clap = { version = "4.0", features = ["derive"] }
git2 = "0.15"
nom = "7.1"
reqwest = { version = "0.11", features = ["json"] }
tempfile = "3.3"

[dev-dependencies]
# Workspace
pretty_assertions.workspace = true
# Crate
assert_cmd = "2.0"

[[bin]]
name = "bencher"
path = "src/main.rs"
