[package]
name = "bencher-cli"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Track Your Benchmarks"
readme = "README.md"
homepage = "https://bencher.dev"
keywords = ["cli", "bench", "benchmark", "benchmarking", "profiling"]
categories = ["command-line-utilities", "development-tools::profiling", "wasm"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
git2 = "0.14.4"
nom = "7.1.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
tempfile = "3.3.0"
thiserror = "1.0.31"
reports = { path = "../lib/reports" }
reqwest = { version = "0.11.10", features = ["json"] }
open = "2.1.2"
url = "2.2.2"
tokio = { version = "1.18.2", features = ["full"] }
email-address-parser = "1.0.3"
