[package]
name = "xtask"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
# Workspace
clap.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
# Crate
anyhow = "1.0"
