[package]
name = "bencher_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
# Crate
axum = "0.5.17"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["tracing-log"] }
