[package]
name = "fn_dba"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dropshot = "0.7.0"
schemars = "0.8.8"
serde = "1.0.137"
tokio = "1.18.1"
slog = "2.7.0"
diesel = { version = "1.4.4", features = ["postgres", "chrono"] }
dotenv = "0.15.0"
util = { path = "../util", features = ["db"] }
chrono = "0.4.19"

[[bin]]
name = "fn_dba"
