[package]
name = "bencher"
version = "0.1.0"
edition = "2021"
description = "Benchmarking Data Tracking"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli = { path = "../cli" }
