[alias]
xtask = "run --manifest-path ./xtask/Cargo.toml --"

[target.'cfg(all()']
rustflags = [
    # https://github.com/rust-lang/rust-clippy
    # warn
    "-Wclippy::all",
    "-Wclippy::pedantic",
    "-Wclippy::restriction",
    "-Wclippy::cargo",
    "-Wclippy::print_stdout",
    "-Wclippy::print_stderr",
    # allow
    "-Aclippy::as_conversions",
    "-Aclippy::cargo_common_metadata",
    "-Aclippy::default_numeric_fallback",
    "-Aclippy::empty_structs_with_brackets",
    "-Aclippy::exhaustive_enums",
    "-Aclippy::exhaustive_structs",
    "-Aclippy::implicit_return",
    "-Aclippy::missing_docs_in_private_items",
    "-Aclippy::missing_errors_doc",
    "-Aclippy::missing_inline_in_public_items",
    "-Aclippy::missing_trait_methods",
    "-Aclippy::mod_module_files",
    "-Aclippy::module_name_repetitions",
    "-Aclippy::multiple_crate_versions",
    "-Aclippy::must_use_candidate",
    "-Aclippy::pattern_type_mismatch",
    "-Aclippy::pub_use",
    "-Aclippy::self_named_module_files",
    "-Aclippy::shadow_reuse",
    "-Aclippy::shadow_same",
    "-Aclippy::single_char_lifetime_names",
    "-Aclippy::std_instead_of_alloc",
    "-Aclippy::std_instead_of_core",
    "-Aclippy::str_to_string",
]
