[package]
name = "util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
db = ["diesel", "chrono"]

[dependencies]
dropshot = "0.7.0"
slog = "2.7.0"
diesel = { version = "1.4.8", optional = true, features = [
    "postgres",
    "chrono",
    "serde_json",
] }
chrono = { version = "0.4.19", optional = true }
serde_json = "1.0.81"
