name: TableFlow Interpreter Deployment
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "Mona the Octocat"
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
# install:
#   - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
#   - if not defined RUSTFLAGS rustup-init.exe -y --default-host x86_64-pc-windows-msvc --default-toolchain nightly
#   - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
#   - rustc -V
#   - cargo -V

# build: false

# test_script:
#   - cargo test --locked
