[package]
name = "bencher_api"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
swagger = ["dep:literally"]

[dependencies]
bencher_json = { path = "../lib/bencher_json", features = ["schema"] }
bencher_rbac = { path = "../lib/bencher_rbac", features = ["json"] }

chrono.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid = { workspace = true, features = ["v4", "serde"] }


dropshot = "0.8"
tokio = "1.21"
slog = "2.7"
email-address-parser = "1.0"
jsonwebtoken = "8.1"
slug = "0.1"
diesel = { version = "2.0", features = ["sqlite", "chrono"] }
diesel_migrations = "2.0"
dotenvy = "0.15"
rand = "0.8"
url = "2.2"
http = "0.2"
ordered-float = "3.0"
statrs = "0.16"
literally = { version = "0.1", optional = true }
lazy_static = "1.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["tracing-log"] }
thiserror = "1.0"
derive_more = "0.99"
oso = "0.26"
mail-send = "0.2.3"
css-inline = "0.8"

[[bin]]
name = "api"
