[package]
name = "bencher_api"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
default = ["plus"]
plus = [
    "bencher_json/plus",
    "dep:bencher_billing",
    "dep:bencher_plus",
    "dep:bencher_license",
]
swagger = ["dep:literally"]

[dependencies]
# Local
bencher_adapter = { path = "../../lib/bencher_adapter" }
bencher_json = { path = "../../lib/bencher_json", features = ["schema"] }
bencher_rbac = { path = "../../lib/bencher_rbac" }
bencher_selfie = { path = "../../lib/bencher_selfie" }
# Plus
bencher_billing = { path = "../../plus/bencher_billing", optional = true }
bencher_plus = { path = "../../plus/bencher_plus", optional = true }
bencher_license = { path = "../../plus/bencher_license", optional = true }
# Workspace
chrono.workspace = true
derive_more.workspace = true
jsonwebtoken.workspace = true
literally = { workspace = true, optional = true }
once_cell.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
ordered-float.workspace = true
oso.workspace = true
rand.workspace = true
slug.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs"] }
url.workspace = true
uuid = { workspace = true, features = ["v4", "serde"] }
# Crate
async-compression = { version = "0.3", features = ["tokio", "gzip"] }
aws-credential-types = "0.54"
aws-sdk-s3 = "0.24"
css-inline = "0.8"
diesel = { version = "2.0", features = ["sqlite", "chrono"] }
diesel_migrations = "2.0"
dropshot = "0.9"
hyper = "0.14"
http = "0.2"
mail-send = "0.3"
slog = "2.7"
statrs = "0.16"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["tracing-log"] }
reqwest = "0.11"

[[bin]]
name = "api"
