[package]
name = "bencher_api"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
swagger = ["dep:literally"]

[dependencies]
# Local
bencher_json = { path = "../lib/bencher_json", features = ["schema"] }
bencher_rbac = { path = "../lib/bencher_rbac", features = ["json"] }
# Workspace
chrono.workspace = true
derive_more.workspace = true
email-address-parser.workspace = true
jsonwebtoken.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
ordered-float.workspace = true
oso.workspace = true
slug.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
uuid = { workspace = true, features = ["v4", "serde"] }
# Crate
dropshot = "0.8"
slog = "2.7"
diesel = { version = "2.0", features = ["sqlite", "chrono"] }
diesel_migrations = "2.0"
dotenvy = "0.15"
rand = "0.8"
http = "0.2"
statrs = "0.16"
literally = { version = "0.1", optional = true }
lazy_static = "1.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["tracing-log"] }
mail-send = "0.2.3"
css-inline = "0.8"

[[bin]]
name = "api"
