app = "bencher-api"
kill_timeout = 6

[build]
image = "registry.fly.io/bencher-api-litestream"

[env]
LITESTREAM_DB_PATH = "/data/bencher.db"

[mounts]
source = "bencher_data"
destination = "/data"

[[services]]
protocol = "tcp"
internal_port = 61016

# [services.concurrency]
# hard_limit = 100
# soft_limit = 50
# type = "connections"

[[services.ports]]
handlers = ["http"]
port = 80
force_https = true

[[services.ports]]
handlers = ["tls", "http"]
port = 443

# [[services.tcp_checks]]
# grace_period = "1s"
# interval = "15s"
# restart_limit = 0
# timeout = "2s"
