app = "bencher-api-dev"
kill_timeout = "6s"

[build]
image = "registry.fly.io/bencher-api-dev"

[[services]]
protocol = "tcp"
internal_port = 61016

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]
