[package]
name = "fn_reports"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
schema = []

[dependencies]
dropshot = "0.7.0"
schemars = "0.8.8"
serde = "1.0.137"
tokio = "1.18.1"
slog = "2.7.0"
reports = { path = "../../lib/reports", features = ["schema"] }
util = { path = "../util", features = ["db"] }
email-address-parser = "1.0.3"
diesel = { version = "1.4.4", features = ["postgres"] }

[[bin]]
name = "fn_reports"
