name: Bencher
description: Installs the Bencher CLI for Continuous Benchmarking
author: Bencher
branding:
  icon: bar-chart
  color: orange
runs:
  using: node16
  main: dist/index.js
inputs:
  version:
    description: "Version of the Bencher CLI to install (ex: 0.1.23) (default latest)"
    default: latest
    required: false
