name: Bencher

on:
  workflow_dispatch:
  push:
    branches: [ main, devel ]
    tags: [v**]
  pull_request:
    branches: [ main, devel ]

env:
  # General
  CARGO_TERM_COLOR: always
  DOCKER_HUB_ORG: bencherdev
  # API
  API_BUILDER_DOCKER_IMAGE: bencher-api-builder
  API_LOCAL_DOCKER_IMAGE: bencher-api-local
  API_LITESTREAM_DOCKER_IMAGE: bencher-api-litestream
  # CLI
  CLI_BIN_NAME: bencher
  CLI_BIN_ARCH: amd64
  CLI_DEB_DIR: deb
  # WASM
  WASM_BENCHER_VALID: bencher-valid-pkg
  # UI
  UI_BUILDER_DOCKER_IMAGE: bencher-ui-builder
  UI_DOCKER_IMAGE: bencher-ui
  UI_BUILD_DIST: bencher-ui-dist

jobs:
  # Pretty
  cargo_fmt:
    name: Cargo Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add fmt
        run: rustup component add rustfmt
      - name: Run fmt
        run: cargo fmt -- --check

  cargo_clippy:
    name: Cargo Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add clippy
        run: rustup component add clippy
      - name: Run clippy
        run: cargo clippy --no-deps -- -Dwarnings

  cargo_udeps:
    name: Cargo Unused Deps
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Install nightly toolchain
        run: rustup toolchain install nightly
      - name: Install udeps
        run: cargo install cargo-udeps --locked
      - name: Run udeps
        run: cargo +nightly udeps

  # Test
  cargo_test:
    name: Cargo Test
    runs-on: ubuntu-latest
    needs:
      - cargo_fmt
      - cargo_clippy
    steps:
      - uses: actions/checkout@v3
      - name: cargo test
        run: RUST_BACKTRACE=1 cargo test -- --nocapture

  # Benchmark
  cargo_bench:
    name: Cargo Bench
    runs-on: ubuntu-latest
    needs: cargo_test
    env:
      BENCHER_PROJECT: bencher
      BENCHER_TESTBED: ubuntu-latest
      BENCHER_ADAPTER: rust
      BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Install nightly toolchain
        run: rustup toolchain install nightly
      - name: Install `bencher` CLI
        run: cargo install --path services/cli --locked
      - name: Dogfooding Benchmarks with Bencher
        run: bencher run --if-branch $GITHUB_REF_NAME --err "cargo +nightly bench"

  # Audit
  cargo_audit:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    name: Cargo Audit
    runs-on: ubuntu-latest
    needs: cargo_test
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  # API Docker
  build_api_docker:
    if: github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/')
    name: Build API (Linux)
    runs-on: ubuntu-latest
    needs: cargo_test
    steps:
      - uses: actions/checkout@v3
      - name: Build Builder Stage
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./services/api/builder.Dockerfile
          tags: ${{ env.API_BUILDER_DOCKER_IMAGE }}
          push: false
      - name: Build Local
        uses: docker/build-push-action@v3
        with:
          context: ./services/api
          file: ./services/api/local.Dockerfile
          tags: ${{ env.DOCKER_HUB_ORG }}/${{ env.API_LOCAL_DOCKER_IMAGE }}
          push: false
      - name: Build Litestream
        uses: docker/build-push-action@v3
        with:
          context: ./services/api
          file: ./services/api/litestream.Dockerfile
          tags: ${{ env.DOCKER_HUB_ORG }}/${{ env.API_LITESTREAM_DOCKER_IMAGE }}
          push: false

  nightly_api_docker:
    if: github.ref == 'refs/heads/main'
    name: Build API and Release Nightly (Linux)
    runs-on: ubuntu-latest
    needs: cargo_test
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build Builder Stage
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./services/api/builder.Dockerfile
          tags: ${{ env.API_BUILDER_DOCKER_IMAGE }}
          push: false
      - name: Build and Push Local to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ./services/api
          file: ./services/api/local.Dockerfile
          tags: ${{ env.DOCKER_HUB_ORG }}/${{ env.API_LOCAL_DOCKER_IMAGE }}:nightly
          push: true
      - name: Build and Push Litestream to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ./services/api
          file: ./services/api/litestream.Dockerfile
          tags: ${{ env.DOCKER_HUB_ORG }}/${{ env.API_LITESTREAM_DOCKER_IMAGE }}:nightly
          push: true

  latest_api_docker:
    if: startsWith(github.ref, 'refs/tags/')
    name: Build API and Release Latest (Linux)
    runs-on: ubuntu-latest
    needs: cargo_test
    steps:
      - uses: actions/checkout@v3
      - name: Export LOCAL_TAGS
        run: |
          export LOCAL_DOCKER_HUB_URL=${{ env.DOCKER_HUB_ORG }}/${API_LOCAL_DOCKER_IMAGE}
          echo "LOCAL_TAGS=${LOCAL_DOCKER_HUB_URL}:latest,${LOCAL_DOCKER_HUB_URL}:${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Export LITESTREAM_TAGS
        run: |
          export LITESTREAM_DOCKER_HUB_URL=${{ env.DOCKER_HUB_ORG }}/${API_LITESTREAM_DOCKER_IMAGE}
          echo "LITESTREAM_TAGS=${LITESTREAM_DOCKER_HUB_URL}:latest,${LITESTREAM_DOCKER_HUB_URL}:${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build Builder Stage
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./services/api/builder.Dockerfile
          tags: ${{ env.API_BUILDER_DOCKER_IMAGE }}
          push: false
      - name: Build and Push Local to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ./services/api
          file: ./services/api/local.Dockerfile
          tags: ${{ env.LOCAL_TAGS }}
          push: true
      - name: Build and Push Litestream to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ./services/api
          file: ./services/api/litestream.Dockerfile
          tags: ${{ env.LITESTREAM_TAGS }}
          push: true

  # CLI
  build_cli_bin:
    name: Build CLI (Linux)
    runs-on: ubuntu-latest
    needs: cargo_test
    steps:
      - uses: actions/checkout@v3
      - name: cargo build CLI
        working-directory: ./services/cli
        run: cargo build --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.CLI_BIN_NAME }}
          path: ./target/release/${{ env.CLI_BIN_NAME }}

  build_cli_deb:
    name: Package CLI (.deb)
    runs-on: ubuntu-latest
    needs: build_cli_bin
    steps:
      - uses: actions/checkout@v3
      - name: export DEB_FILE
        run: echo "DEB_FILE=${CLI_BIN_NAME}_$(./scripts/version.sh)_${CLI_BIN_ARCH}.deb" >> $GITHUB_ENV
      - name: Download CLI Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.CLI_BIN_NAME }}
      - name: Build .deb package
        run: ./scripts/deb.sh $CLI_BIN_NAME $(./scripts/version.sh) $CLI_BIN_ARCH $CLI_DEB_DIR
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.DEB_FILE }}
          path: ${{ env.CLI_DEB_DIR }}/${{ env.DEB_FILE }}

  release_cli_deb:
    if: startsWith(github.ref, 'refs/tags/')
    name: Release CLI
    runs-on: ubuntu-latest
    needs:
      - cargo_bench
      - build_cli_deb
      - latest_api_docker
      - latest_ui_docker
    steps:
      - uses: actions/checkout@v3
      - name: export DEB_FILE
        run: echo "DEB_FILE=${CLI_BIN_NAME}_$(./scripts/version.sh)_${CLI_BIN_ARCH}.deb" >> $GITHUB_ENV
      - name: Download CLI bin artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.CLI_BIN_NAME }}
      - name: Download CLI .deb Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.DEB_FILE }}
      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.CLI_BIN_NAME }}
            ${{ env.DEB_FILE }}

  # UI Docker
  build_ui_docker:
    if: github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/')
    name: Build UI (Linux)
    runs-on: ubuntu-latest
    needs: cargo_test
    steps:
      - uses: actions/checkout@v3
      - name: Build Builder Stage
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./services/ui/builder.Dockerfile
          tags: ${{ env.UI_BUILDER_DOCKER_IMAGE }}
          push: false
      - name: Build UI
        uses: docker/build-push-action@v3
        with:
          context: ./services/ui
          tags: ${{ env.DOCKER_HUB_ORG }}/${{ env.UI_DOCKER_IMAGE }}
          push: false

  nightly_ui_docker:
    if: github.ref == 'refs/heads/main'
    name: Build UI and Release Nightly (Linux)
    runs-on: ubuntu-latest
    needs: cargo_test
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build Builder Stage
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./services/ui/builder.Dockerfile
          tags: ${{ env.UI_BUILDER_DOCKER_IMAGE }}
          push: false
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ./services/ui
          tags: ${{ env.DOCKER_HUB_ORG }}/${{ env.UI_DOCKER_IMAGE }}:nightly
          push: true

  latest_ui_docker:
    if: startsWith(github.ref, 'refs/tags/')
    name: Build UI and Release Latest (Linux)
    runs-on: ubuntu-latest
    needs: cargo_test
    steps:
      - uses: actions/checkout@v3
      - name: export TAGS
        run: |
          export DOCKER_HUB_URL=${{ env.DOCKER_HUB_ORG }}/${UI_DOCKER_IMAGE}
          echo "TAGS=${DOCKER_HUB_URL}:latest,${DOCKER_HUB_URL}:${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build Builder Stage
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./services/ui/builder.Dockerfile
          tags: ${{ env.UI_BUILDER_DOCKER_IMAGE }}
          push: false
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ./services/ui
          tags: ${{ env.TAGS }}
          push: true

  # UI WASM
  build_bencher_valid_wasm:
    name: Build `bencher_valid` WASM
    runs-on: ubuntu-latest
    needs: cargo_test
    steps:
      - uses: actions/checkout@v3
      - uses: jetli/wasm-pack-action@v0.3.0
      - name: WASM pack `bencher_valid`
        working-directory: ./lib/bencher_valid
        run: wasm-pack build --target web --no-default-features --features wasm
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.WASM_BENCHER_VALID }}
          path: ./lib/bencher_valid/pkg

  # UI
  build_ui:
    name: Build UI
    runs-on: ubuntu-latest
    needs: build_bencher_valid_wasm
    steps:
      - uses: actions/checkout@v3
      - name: Download `bencher_valid` Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.WASM_BENCHER_VALID }}
          path: ./lib/bencher_valid/pkg
      - name: Build UI
        working-directory: ./services/ui
        run: |
          npm install
          npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.UI_BUILD_DIST }}
          path: ./services/ui/dist

  # API Fly.io
  deploy_api_fly:
    name: Deploy API to Fly.io
    runs-on: ubuntu-latest
    needs:
      - nightly_api_docker
      - build_ui
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy API to Fly.io
        working-directory: ./services/api
        run: flyctl deploy --remote-only

  # UI Netlify
  deploy_ui_netlify:
    if: github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/')
    name: Deploy UI to Netlify
    runs-on: ubuntu-latest
    needs: build_ui
    steps:
      - uses: actions/checkout@v3
      - name: Download UI Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.UI_BUILD_DIST }}
          path: ./services/ui/dist
      - uses: netlify/actions/cli@master
        with:
          args: deploy --dir ./services/ui/dist --alias ${GITHUB_REF#refs/*/} --message "${{ github.event.head_commit.message }}"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

  deploy_ui_netlify_prod:
    name: Deploy UI to Netlify Prod
    runs-on: ubuntu-latest
    needs: deploy_api_fly
    steps:
      - uses: actions/checkout@v3
      - name: Download UI Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.UI_BUILD_DIST }}
          path: ./services/ui/dist
      - uses: netlify/actions/cli@master
        with:
          args: deploy --dir ./services/ui/dist --alias ${GITHUB_REF#refs/*/} --message "${{ github.event.head_commit.message }}" --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}