name: Bencher

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build CLI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cargo build CLI
        working-directory: ./services/cli
        run: cargo build --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: bencher
          path: target/release/bencher

  deb:
    name: .deb Package CLI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download CLI Artifact
        uses: actions/download-artifact@v3
        with:
          name: bencher
      - uses: kentik/pkg@v1
        with:
          name: bencher
          version: 0.1.0
          arch: x86_64
          format: deb
          package: ./services/cli/pkg.yml
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: bencher.deb
          path: bencher.deb