name: Bencher

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build CLI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: cargo build CLI
        working-directory: ./services/cli
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: bencher
          path: target/release/bencher
