name: Bencher

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  BIN_NAME: bencher
  BIN_VERSION: 0.1.0
  BIN_ARCH: amd64

jobs:
  cli_build_linux:
    name: Build CLI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cargo build CLI
        working-directory: ./services/cli
        run: cargo build --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: bencher
          path: target/release/bencher

  cli_package_deb:
    name: Package CLI (.deb)
    needs: cli_build_linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download CLI Artifact
        uses: actions/download-artifact@v3
        with:
          name: bencher
      - name: Build .deb package
        run: ./scripts/deb.sh $BIN_NAME $BIN_VERSION $BIN_ARCH
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BIN_NAME }}_${{ env.BIN_VERSION }}_${{ env.BIN_ARCH }}.deb
          path: ${{ env.BIN_NAME }}_${{ env.BIN_VERSION }}_${{ env.BIN_ARCH }}.deb