name: Bencher

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build CLI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cargo build CLI
        working-directory: ./services/cli
        run: cargo build --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: bencher
          path: target/release/bencher
