name: Release UI

on:
  workflow_dispatch:
  push:
    branches: [ master, devel ]
    tags: [v**]
  pull_request:
    branches: [ master, devel ]

env:
  CARGO_TERM_COLOR: always
  DOCKER_IMAGE: bencher-ui

jobs:
  build_ui_docker:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    name: Build UI (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ./services/ui
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest
          push: false

  release_ui_docker:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    name: Build and Release UI (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: export TAGS
        run: |
          export DOCKER_HUB_URL=${{ secrets.DOCKER_HUB_USERNAME }}/${DOCKER_IMAGE}
          echo "TAGS=${DOCKER_HUB_URL}:latest,${DOCKER_HUB_URL}:${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ./services/ui
          tags: ${{ env.TAGS }}
          push: true
