name: Dependabot for Actions

on:
  workflow_dispatch:
  push:
    branches: [ master ]

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
