name: Release API

on:
  workflow_dispatch:
  push:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  BUILDER_DOCKER_IMAGE: bencher-api-builder
  LOCAL_DOCKER_IMAGE: bencher-api-local
  LITESTREAM_DOCKER_IMAGE: bencher-api-litestream

jobs:
  api_build_linux:
    name: Build API (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Export LOCAL_TAGS
        run: |
          export LOCAL_DOCKER_HUB_URL=${{ secrets.DOCKER_HUB_USERNAME }}/${LOCAL_DOCKER_IMAGE}
          echo "LOCAL_TAGS=${LOCAL_DOCKER_HUB_URL}:latest,${LOCAL_DOCKER_HUB_URL}:$(./scripts/version.sh)" >> $GITHUB_ENV
      - name: Export LITESTREAM_TAGS
        run: |
          export LITESTREAM_DOCKER_HUB_URL=${{ secrets.DOCKER_HUB_USERNAME }}/${LITESTREAM_DOCKER_IMAGE}
          echo "LITESTREAM_TAGS=${LITESTREAM_DOCKER_HUB_URL}:latest,${LITESTREAM_DOCKER_HUB_URL}:$(./scripts/version.sh)" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build Builder Stage
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./services/api/build.Dockerfile
          tags: ${{ env.BUILDER_DOCKER_IMAGE }}
          push: false
      - name: Build and Push Local to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ./services/api
          file: ./services/api/local.Dockerfile
          tags: ${{ env.LOCAL_TAGS }}
          push: true
      - name: Build and Push Litestream to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ./services/api
          file: ./services/api/litestream.Dockerfile
          tags: ${{ env.LITESTREAM_TAGS }}
          push: true
