name: Release CLI

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build Rust]
    types: [completed]

env:
  CARGO_TERM_COLOR: always
  BIN_NAME: bencher
  BIN_ARCH: amd64

jobs:
  release_cli:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && startsWith(github.ref, 'refs/tags/')
    name: Release CLI
    needs: cli_package_deb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: export DEB_FILE
        run: echo "DEB_FILE=${BIN_NAME}_$(./scripts/version.sh)_${BIN_ARCH}.deb" >> $GITHUB_ENV
      - name: Download CLI bin artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.BIN_NAME }}
      - name: Download CLI .deb Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.DEB_FILE }}
      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.BIN_NAME }}
            ${{ env.DEB_FILE }}