name: Release UI

on:
  workflow_dispatch:
  push:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  DOCKER_IMAGE: bencher-ui

jobs:
  api_build_linux:
    name: Build UI (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: export TAGS
        run: |
          export DOCKER_HUB_URL=${{ secrets.DOCKER_HUB_USERNAME }}/${DOCKER_IMAGE}
          echo "TAGS=${DOCKER_HUB_URL}:latest,${DOCKER_HUB_URL}:$(./scripts/version.sh)" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ./services/ui
          tags: ${{ env.TAGS }}
          push: true
